### ISSUE TITLE
Negative numbers allowed for age and height

### ISSUE THREAD

**Issue by yakryder** [SherSpock/muscle-wizards#28]
Currently negative numbers are allowed for age and height on both the sign up form and in the actual record that is saved to the database.

![mw sign-up](https://cloud.githubusercontent.com/assets/14241275/15100218/dac37a7e-1539-11e6-8b24-cb2ef8b36364.jpg)
![screen shot 2016-05-08 at 4 22 54 pm](https://cloud.githubusercontent.com/assets/14241275/15100219/dacfcfd6-1539-11e6-90ec-d55651f9c927.jpg)

**Comment by sbaughman** [comment]
fixed with commits on users branch for registration and user edit forms.
