### ISSUE TITLE
Simplify path helpers

### ISSUE THREAD

**Issue by dummied** [SherSpock/muscle-wizards#68]
A few examples:

https://github.com/SherSpock/muscle-wizards/blob/master/app/controllers/conversations_controller.rb#L12

`prep_conversation_messages_path(@prep, @conversation)`

https://github.com/SherSpock/muscle-wizards/blob/master/app/controllers/preps_controller.rb#L14

`redirect_to @prep`

Reasonably sure there are more in there (haven't looked at views yet, for instance)

**Comment by dummied** [comment]
https://github.com/SherSpock/muscle-wizards/blob/master/app/controllers/target_cardios_controller.rb#L19

`redirect_to @prep`

**Comment by dummied** [comment]
https://github.com/SherSpock/muscle-wizards/blob/master/app/controllers/certifications_controller.rb#L13
https://github.com/SherSpock/muscle-wizards/blob/master/app/controllers/certifications_controller.rb#L27
https://github.com/SherSpock/muscle-wizards/blob/master/app/controllers/certifications_controller.rb#L36

`redirect_to current_user`

**Comment by sbaughman** [comment]
fixed with debug branch
