### ISSUE TITLE
Use the proxy

### ISSUE THREAD

**Issue by dummied** [SherSpock/muscle-wizards#69]
Rather than setting the prep (this is most-common case I've seen) after instantiating an object, use the prep proxy instead.

As in:

https://github.com/SherSpock/muscle-wizards/blob/master/app/controllers/target_cardios_controller.rb#L15-L16

``` ruby
@target_cardio = @prep.target_cardios.new(target_cardio_params)
```

There are more than this one example.

**Comment by dummied** [comment]
https://github.com/SherSpock/muscle-wizards/blob/master/app/controllers/certifications_controller.rb#L9-L10

`current_user.certifications.new ...`

**Comment by sbaughman** [comment]
fixed with debug branch
